[package]
name = "rust_carbon_desktop_app"
version = "0.1.0"
authors = ["Anthony H <anthony@hevia.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = "0.3"