[package]
name = "rust_neural_network"
version = "0.1.0"
authors = ["Anthony Hevia <anthonyhevia@microsoft.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cogent = "0.6.3"